### ISSUE TITLE
Repo Layout Change

### ISSUE THREAD

**Issue by C4Wiz** [mammo0/Repository-Bootstrapper#4]
i am trying to change the way my repo is structured.

i am trying to manage 2 version of the same skin, Matrix and Nexus.

i have created subfolders under the skin name to reflect this. 
IE:

skin.my.skin/Matrix/
skin.my.skin/Nexux/

but the script does not understand this setup. is this easy to fix in the repo script?

**Comment by mammo0** [comment]
>  is this easy to fix in the repo script?

No, the behaviour that you describe is currently not possible. And I think a corresponding change would need a lot of extra work.

I'm sorry but since I don't need that functionality, I won' t implement it. But feel free to adapt my script.

Another thought: Why don't you create separate plugins for each Kodi version:

- skin.my.skin.matrix
- skin.my.skin.nexus

**Comment by C4Wiz** [comment]
> 

yea i ended up just appending the kodi version to the skin name.

**Comment by mammo0** [comment]
Allright, then I will close this.
